# Generated by Django 4.0.5 on 2022-07-03 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должность',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=15, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('employment_date', models.DateField(verbose_name='Прием на работу')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='Зарплата')),
                ('chief', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='employees.job', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудник',
            },
        ),
    ]
